[package]
name = "tp_engine"
version = "3.0.0"
edition = "2021"
rust-version = "1.56"  # Rust 2021

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
